"""
Grad-CAM Heatmap & Explainability Viewer Component (Phase 4)
Displays visual saliency attention maps and alpha-blended overlays generated by convolutional neural networks.
Provides clean pending-integration placeholders and interactive opacity blending controls.
"""

from typing import Any, Optional
import numpy as np
import cv2
from PIL import Image
import streamlit as st
from app.components.fundus_viewer import render_fundus_viewer


def blend_heatmap_on_image(
    image: Image.Image,
    heatmap: np.ndarray,
    alpha: float = 0.45
) -> Image.Image:
    """
    Overlay a 2D float heatmap (0.0 - 1.0) onto a fundus image using the JET colormap.
    Returns composite PIL Image.
    """
    np_img = np.array(image.convert("RGB"))
    h, w, _ = np_img.shape
    
    # Normalize heatmap to uint8 (0 - 255)
    norm_heat = np.uint8(255 * np.clip(heatmap, 0.0, 1.0))
    # Resize heatmap to match image dimensions
    resized_heat = cv2.resize(norm_heat, (w, h))
    
    # Apply JET colormap (RGB format)
    colored_heat_bgr = cv2.applyColorMap(resized_heat, cv2.COLORMAP_JET)
    colored_heat_rgb = cv2.cvtColor(colored_heat_bgr, cv2.COLOR_BGR2RGB)
    
    # Alpha blend
    blended = np.uint8(np_img * (1.0 - alpha) + colored_heat_rgb * alpha)
    return Image.fromarray(blended)


def render_gradcam_viewer(
    original_image: Any,
    gradcam_heatmap: Optional[Any] = None,
    gradcam_overlay: Optional[Any] = None,
    default_view_mode: str = "Side-by-Side"
) -> None:
    """
    Render Grad-CAM visualizations with interactive viewing options.
    
    If gradcam output is None, renders a clear clinical placeholder
    explaining that the explainability pipeline is awaiting real AI integration.
    """
    if isinstance(original_image, Image.Image):
        pil_orig = original_image
    elif isinstance(original_image, np.ndarray):
        pil_orig = Image.fromarray(original_image)
    else:
        pil_orig = original_image

    if gradcam_heatmap is None and gradcam_overlay is None:
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("##### 👁️ Input Retinal Fundus")
            render_fundus_viewer(pil_orig, caption="45° Posterior Pole")
            
        with col2:
            st.markdown("##### 🧠 Grad-CAM Attention Heatmap")
            st.markdown(
                """
                <div style="
                    border: 2px dashed #cbd5e1;
                    border-radius: 8px;
                    padding: 50px 20px;
                    text-align: center;
                    background-color: #f8fafc;
                    color: #475569;
                ">
                    <div style="font-size: 32px; margin-bottom: 8px;">🔬</div>
                    <div style="font-size: 15px; font-weight: 700; color: #1e293b;">
                        Grad-CAM Saliency Output Pending
                    </div>
                    <div style="font-size: 13px; color: #64748b; margin-top: 6px; line-height: 1.5;">
                        The AI explainability module will calculate gradient-weighted class activation 
                        maps highlighting retinal regions that trigger the DR severity prediction.
                    </div>
                    <div style="
                        display: inline-block;
                        margin-top: 14px;
                        background: #e2e8f0;
                        color: #334155;
                        font-size: 11px;
                        font-weight: 700;
                        padding: 4px 10px;
                        border-radius: 4px;
                    ">
                        AWAITING REAL MODEL INTEGRATION
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )
        return

    # If Grad-CAM heatmap array is available:
    view_tab1, view_tab2 = st.tabs(["🖼️ Side-by-Side Comparison", "🎛️ Interactive Opacity Overlay"])
    
    with view_tab1:
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("##### Input Fundus")
            render_fundus_viewer(pil_orig, caption="Original Photograph")
        with col2:
            st.markdown("##### Grad-CAM Attention Saliency")
            if isinstance(gradcam_heatmap, np.ndarray):
                overlay = blend_heatmap_on_image(pil_orig, gradcam_heatmap, alpha=0.50)
                render_fundus_viewer(overlay, caption="CNN Attention Overlay (JET Colormap)")
            else:
                render_fundus_viewer(gradcam_overlay or gradcam_heatmap, caption="Grad-CAM Overlay")

    with view_tab2:
        col_ctrl, col_img = st.columns([1, 2])
        with col_ctrl:
            st.markdown("##### Heatmap Blend Controls")
            alpha = st.slider(
                "Heatmap Overlay Opacity",
                min_value=0.0,
                max_value=1.0,
                value=0.45,
                step=0.05,
                help="Adjust the transparency of the saliency map over the raw fundus photograph."
            )
            st.caption("0.0 = Raw Fundus Only | 1.0 = Pure Saliency Heatmap")
            
        with col_img:
            if isinstance(gradcam_heatmap, np.ndarray):
                interactive_overlay = blend_heatmap_on_image(pil_orig, gradcam_heatmap, alpha=alpha)
                render_fundus_viewer(interactive_overlay, caption=f"Blended Saliency (Opacity: {int(alpha*100)}%)")
            else:
                render_fundus_viewer(gradcam_overlay, caption="Grad-CAM Saliency Map")
