"""
Lesion Evidence & Segmentation Overlay Component
Displays lesion counts and segmentation masks (Microaneurysms, Hemorrhages, Exudates)
strictly based on values returned by the AI pipeline.
"""

from typing import Any, Dict, Optional
import streamlit as st
from app.components.fundus_viewer import render_fundus_viewer


def render_lesion_summary_cards(lesions: Dict[str, int]) -> None:
    """
    Render 4 clinical lesion count cards.
    Displays EXACT counts provided by the AI pipeline.
    """
    ma_count = lesions.get("microaneurysms", 0)
    hem_count = lesions.get("hemorrhages", 0)
    he_count = lesions.get("hard_exudates", 0)
    se_count = lesions.get("soft_exudates", 0)
    
    col1, col2, col3, col4 = st.columns(4)
    
    cards = [
        (col1, "Microaneurysms", ma_count, "#3b82f6", "Early vascular out-pouching"),
        (col2, "Hemorrhages", hem_count, "#ef4444", "Intraretinal flame/dot-blot bleeds"),
        (col3, "Hard Exudates", he_count, "#f59e0b", "Lipid/protein deposits"),
        (col4, "Soft Exudates (Cotton Wool)", se_count, "#8b5cf6", "Nerve fiber layer infarcts"),
    ]
    
    for col, title, count, color, desc in cards:
        with col:
            st.markdown(
                f"""
                <div style="
                    background: #ffffff;
                    border: 1px solid #e2e8f0;
                    border-top: 4px solid {color};
                    border-radius: 8px;
                    padding: 14px;
                    box-shadow: 0 1px 2px rgba(0,0,0,0.03);
                ">
                    <div style="font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase;">
                        {title}
                    </div>
                    <div style="font-size: 26px; font-weight: 700; color: #0f172a; margin: 4px 0;">
                        {count} <span style="font-size: 12px; font-weight: 400; color: #64748b;">detected</span>
                    </div>
                    <div style="font-size: 11px; color: #94a3b8;">
                        {desc}
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )


def render_lesion_mask_viewer(
    original_image: Any,
    lesion_overlay: Optional[Any] = None,
    vessel_mask: Optional[Any] = None
) -> None:
    """Render original fundus side-by-side with retinal vessel mask / lesion overlay."""
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("#### Retinal Fundus")
        render_fundus_viewer(original_image, caption="Base Image")
        
    with col2:
        st.markdown("#### Lesion & Vessel Segmentation")
        if lesion_overlay is not None or vessel_mask is not None:
            render_fundus_viewer(lesion_overlay or vessel_mask, caption="Lesion / Vessel Map")
        else:
            st.markdown(
                """
                <div style="
                    border: 2px dashed #cbd5e1;
                    border-radius: 8px;
                    padding: 50px 20px;
                    text-align: center;
                    background-color: #f8fafc;
                    color: #475569;
                ">
                    <div style="font-size: 26px; margin-bottom: 8px;">🩸</div>
                    <div style="font-size: 14px; font-weight: 600; color: #1e293b;">
                        Lesion Mask Segmentation
                    </div>
                    <div style="font-size: 12px; color: #64748b; margin-top: 4px;">
                        Lesion contour overlays and vessel segmentations will be generated by the AI segmentation pipeline.
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )
